In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv("E:/Ecommerce Returns/E-commerce Return Rate Reduction Analysis.csv")
print(data)

         Order_ID    Product_ID       User_ID  Order_Date Product_Category  \
0     ORD00000000  PROD00000000  USER00000000  08-05-2023         Clothing
1     ORD00000001  PROD00000001  USER00000001  10-09-2023            Books
2     ORD00000002  PROD00000002  USER00000002  05-06-2023             Toys
3     ORD00000003  PROD00000003  USER00000003   8/29/2024             Toys
4     ORD00000004  PROD00000004  USER00000004   1/16/2023            Books
...           ...           ...           ...         ...              ...
9995  ORD00009995  PROD00009995  USER00009995  10/20/2023             Home
9996  ORD00009996  PROD00009996  USER00009996   2/25/2023      Electronics
9997  ORD00009997  PROD00009997  USER00009997  05-10-2024             Toys
9998  ORD00009998  PROD00009998  USER00009998   2/13/2024             Toys
9999  ORD00009999  PROD00009999  USER00009999  12-08-2024             Toys

      Product_Price  Order_Quantity  User_Age User_Gender User_Location  \
0            411.59               3        58        Male        City54
1            288.88               3        68      Female        City85
2            390.03               5        22      Female        City30
3            401.09               3        40        Male        City95
4            110.09               4        34      Female        City80
...             ...             ...       ...         ...           ...
9995         142.50               4        37        Male        City40
9996         484.63               3        69        Male        City62
9997         386.57               5        46        Male        City74
9998         129.22               1        34      Female        City34
9999         459.42               5        24      Female        City51

     Payment_Method Shipping_Method  Discount_Applied Return_Date  \
0        Debit Card        Next-Day             45.27   8/26/2024
1       Credit Card         Express             47.79  11-09-2023
2        Debit Card        Next-Day             26.64         NaN
3            PayPal        Next-Day             15.37         NaN
4         Gift Card        Standard             16.37         NaN
...             ...             ...               ...         ...
9995         PayPal        Standard             34.27         NaN
9996     Debit Card         Express             25.44         NaN
9997    Credit Card        Next-Day             12.67         NaN
9998      Gift Card         Express             49.97         NaN
9999     Debit Card         Express             16.05  09-09-2024

      Return_Status
0                 1
1                 1
2                 0
3                 0
4                 0
...             ...
9995              0
9996              0
9997              0
9998              0
9999              1

[10000 rows x 15 columns]

In [2]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  str
 1   Product_ID        10000 non-null  str
 2   User_ID           10000 non-null  str
 3   Order_Date        10000 non-null  str
 4   Product_Category  10000 non-null  str
 5   Product_Price     10000 non-null  float64
 6   Order_Quantity    10000 non-null  int64
 7   User_Age          10000 non-null  int64
 8   User_Gender       10000 non-null  str
 9   User_Location     10000 non-null  str
 10  Payment_Method    10000 non-null  str
 11  Shipping_Method   10000 non-null  str
 12  Discount_Applied  10000 non-null  float64
 13  Return_Date       5052 non-null   str
 14  Return_Status     10000 non-null  int64
dtypes: float64(2), int64(3), str(10)
memory usage: 1.9 MB

In [3]:
data.describe()

,Product_Price,Order_Quantity,User_Age,Discount_Applied,Return_Status
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,252.369307,3.006100,44.195000,24.992162,0.505200
std,142.883865,1.406791,15.311983,14.363396,0.499998
min,5.010000,1.000000,18.000000,0.000000,0.000000
25%,128.650000,2.000000,31.000000,12.752500,0.000000
50%,250.445000,3.000000,44.000000,24.840000,1.000000
75%,377.837500,4.000000,57.000000,37.605000,1.000000
max,499.890000,5.000000,70.000000,50.000000,1.000000

In [4]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [5]:
data.isnull().sum()

Order_ID               0
Product_ID             0
User_ID                0
Order_Date             0
Product_Category       0
Product_Price          0
Order_Quantity         0
User_Age               0
User_Gender            0
User_Location          0
Payment_Method         0
Shipping_Method        0
Discount_Applied       0
Return_Date         4948
Return_Status          0
dtype: int64

In [6]:
data.shape

(10000, 15)

In [7]:
data.isnull().sum().sort_values(ascending=False)

Return_Date         4948
Product_ID             0
Order_ID               0
Order_Date             0
Product_Category       0
Product_Price          0
User_ID                0
Order_Quantity         0
User_Age               0
User_Location          0
User_Gender            0
Payment_Method         0
Shipping_Method        0
Discount_Applied       0
Return_Status          0
dtype: int64

In [8]:
data['Return_Status'].value_counts()

Return_Status
1    5052
0    4948
Name: count, dtype: int64

In [9]:
data['Return_Status'].value_counts(normalize=True)*100

Return_Status
1    50.52
0    49.48
Name: proportion, dtype: float64

In [10]:
return_rate=data['Return_Status'].mean()*100
print(f'Overall Return Rate={return_rate:.2f}%')

Overall Return Rate=50.52%

In [11]:
category_return=(
                data.groupby('Product_Category')['Return_Status'].mean().sort_values(ascending=False)
                )
category_return

Product_Category
Clothing       0.524500
Electronics    0.509320
Books          0.506614
Toys           0.495370
Home           0.490148
Name: Return_Status, dtype: float64

In [31]:
location_return=(
                data.groupby('User_Location')['Return_Status'].mean().mul(100).sort_values(ascending=False)
                )
location_return

User_Location
City68    62.105263
City71    61.764706
City87    61.111111
City10    59.803922
City19    58.762887
            ...
City45    41.836735
City46    41.584158
City41    41.573034
City32    39.814815
City25    38.775510
Name: Return_Status, Length: 100, dtype: float64

In [13]:
data.dtypes

Order_ID                str
Product_ID              str
User_ID                 str
Order_Date              str
Product_Category        str
Product_Price       float64
Order_Quantity        int64
User_Age              int64
User_Gender             str
User_Location           str
Payment_Method          str
Shipping_Method         str
Discount_Applied    float64
Return_Date             str
Return_Status         int64
dtype: object

In [14]:
data['Order_Date']=pd.to_datetime(data['Order_Date'],
                                   format='mixed',
                                   errors='coerce')

In [15]:
data['Return_Date']=pd.to_datetime(
                    data['Return_Date'],
                    format='mixed',
                    errors='coerce'
    
)

In [16]:
data[['Order_Date','Return_Date']].head(10)

  Order_Date Return_Date
0 2023-08-05  2024-08-26
1 2023-10-09  2023-11-09
2 2023-05-06         NaT
3 2024-08-29         NaT
4 2023-01-16         NaT
5 2024-02-14  2024-09-22
6 2023-05-29  2023-08-03
7 2023-02-09  2024-08-01
8 2024-12-25  2024-09-25
9 2023-03-10  2024-01-21

In [17]:
data[data['Return_Status']==1]['Return_Date'].isna().sum()

np.int64(0)

In [18]:
print(data.groupby('Return_Status')['Return_Date'].apply(lambda x:x.isna().sum()))

Return_Status
0    4948
1       0
Name: Return_Date, dtype: int64

In [19]:
data.dtypes

Order_ID                       str
Product_ID                     str
User_ID                        str
Order_Date          datetime64[us]
Product_Category               str
Product_Price              float64
Order_Quantity               int64
User_Age                     int64
User_Gender                    str
User_Location                  str
Payment_Method                 str
Shipping_Method                str
Discount_Applied           float64
Return_Date         datetime64[us]
Return_Status                int64
dtype: object

In [20]:
data.duplicated().sum()

np.int64(0)

In [21]:
data['Order_ID'].duplicated().sum()

np.int64(0)

In [22]:
data[['Product_Price', 'Order_Quantity', 'User_Age', 'Discount_Applied']].describe()

       Product_Price  Order_Quantity      User_Age  Discount_Applied
count   10000.000000    10000.000000  10000.000000      10000.000000
mean      252.369307        3.006100     44.195000         24.992162
std       142.883865        1.406791     15.311983         14.363396
min         5.010000        1.000000     18.000000          0.000000
25%       128.650000        2.000000     31.000000         12.752500
50%       250.445000        3.000000     44.000000         24.840000
75%       377.837500        4.000000     57.000000         37.605000
max       499.890000        5.000000     70.000000         50.000000

In [23]:
print(data['Product_Category'].value_counts())

Product_Category
Books          2041
Home           2030
Clothing       2000
Electronics    1985
Toys           1944
Name: count, dtype: int64

In [24]:
print(data['User_Gender'].value_counts())

User_Gender
Female    5052
Male      4948
Name: count, dtype: int64

In [25]:
print(data['Payment_Method'].value_counts())

Payment_Method
Gift Card      2537
Debit Card     2510
PayPal         2480
Credit Card    2473
Name: count, dtype: int64

In [26]:
print(data['Shipping_Method'].value_counts())

Shipping_Method
Next-Day    3394
Express     3306
Standard    3300
Name: count, dtype: int64

In [29]:
shipping_return_rate = (
    data.groupby('Shipping_Method')['Return_Status']
      .mean().mul(100)
      .sort_values(ascending=False)
)

shipping_return_rate

Shipping_Method
Next-Day    51.090159
Standard    50.515152
Express     49.939504
Name: Return_Status, dtype: float64

In [33]:
# payment_return_rate 
payment_return_rate = (
    data.groupby('Payment_Method')['Return_Status']
      .mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
)

payment_return_rate

Payment_Method
Gift Card      51.60
Debit Card     51.12
Credit Card    50.51
PayPal         48.83
Name: Return_Status, dtype: float64

In [35]:
gender_return_rate = (
    data.groupby('User_Gender')['Return_Status']
      .mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
)

gender_return_rate

User_Gender
Female    50.57
Male      50.46
Name: Return_Status, dtype: float64

In [37]:
# Calculating discount band 

data['Discount_band']=pd.cut(data['Discount_Applied'],
                             bins=[-1,10,20,30,40,50],
                             labels=['0-10%','11-20%','21-30%','31-40%','41-50%'])

In [38]:
print(data['Discount_band'])

0       41-50%
1       41-50%
2       21-30%
3       11-20%
4       11-20%
         ...
9995    31-40%
9996    21-30%
9997    11-20%
9998    41-50%
9999    11-20%
Name: Discount_band, Length: 10000, dtype: category
Categories (5, str): ['0-10%' < '11-20%' < '21-30%' < '31-40%' < '41-50%']

In [41]:
discount_return_rate = (
    data.groupby('Discount_band')['Return_Status']
      .mean()
      .mul(100)
      .round(2)
)

discount_return_rate

Discount_band
0-10%     48.20
11-20%    48.64
21-30%    52.96
31-40%    51.48
41-50%    51.38
Name: Return_Status, dtype: float64

In [55]:
product_return_rate['Total_Orders'].value_counts().sort_index()

Total_Orders
1    10000
Name: count, dtype: int64

In [ ]:
# **Note:** Each Product_ID appears only once in the dataset.
# Therefore, historical product-level return rates cannot be reliably calculated. 
# High-risk products will instead be identified using predicted return probability from the Logistic Regression model.

# **Insight:** Monthly return rates fluctuated between 47.12% and 54.95%. August 2024 recorded the highest return rate (54.95%), while June 2024 recorded the lowest (47.12%). Overall, returns show fluctuations rather than a consistent upward or downward trend.

In [60]:
category_discount_return = (
    data.groupby(['Product_Category', 'Discount_band'], observed=True)['Return_Status']
        .mean()
        .mul(100)
        .round(2)
        .reset_index()
)

category_discount_return

   Product_Category Discount_band  Return_Status
0             Books         0-10%          46.52
1             Books        11-20%          48.35
2             Books        21-30%          50.86
3             Books        31-40%          54.19
4             Books        41-50%          53.02
5          Clothing         0-10%          51.16
6          Clothing        11-20%          48.48
7          Clothing        21-30%          53.47
8          Clothing        31-40%          53.65
9          Clothing        41-50%          55.73
10      Electronics         0-10%          48.96
11      Electronics        11-20%          47.67
12      Electronics        21-30%          55.44
13      Electronics        31-40%          51.00
14      Electronics        41-50%          51.72
15             Home         0-10%          45.48
16             Home        11-20%          48.94
17             Home        21-30%          50.50
18             Home        31-40%          51.21
19             Home        41-50%          48.96
20             Toys         0-10%          48.64
21             Toys        11-20%          49.76
22             Toys        21-30%          54.76
23             Toys        31-40%          47.11
24             Toys        41-50%          47.51

In [61]:
 # Logistic Regression – Return Prediction


features = [
    'Product_Category',
    'Product_Price',
    'Order_Quantity',
    'User_Age',
    'User_Gender',
    'User_Location',
    'Payment_Method',
    'Shipping_Method',
    'Discount_Applied'
]

X = data[features]
y = data['Return_Status']

In [62]:
print(X.shape)
print(y.shape)

(10000, 9)
(10000,)

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [64]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 9)
(2000, 9)
(8000,)
(2000,)

In [66]:
categorical_features = [
    'Product_Category',
    'User_Gender',
    'User_Location',
    'Payment_Method',
    'Shipping_Method'
]

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

In [68]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

In [69]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Product_Category',
                                                   'User_Gender',
                                                   'User_Location',
                                                   'Payment_Method',
                                                   'Shipping_Method'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [71]:
y_pred = model.predict(X_test)

In [72]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.496

In [73]:
print(pd.Series(y_pred).value_counts())

1    1106
0     894
Name: count, dtype: int64

In [74]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.49      0.44      0.46       990
           1       0.50      0.55      0.52      1010

    accuracy                           0.50      2000
   macro avg       0.50      0.50      0.49      2000
weighted avg       0.50      0.50      0.49      2000

In [75]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[438 552]
 [456 554]]

In [76]:
return_probability = model.predict_proba(X_test)[:, 1]

print(return_probability[:10])

[0.48092597 0.54337437 0.54963137 0.48391351 0.53689294 0.5304452
 0.58691596 0.46514014 0.35238017 0.51723913]

In [77]:
risk_score = (return_probability * 100).round(2)

print(risk_score[:10])

[48.09 54.34 54.96 48.39 53.69 53.04 58.69 46.51 35.24 51.72]

In [84]:
risk_level = pd.cut(
    risk_score,
    bins=[-1, 40, 70, 100],
    labels=['Low', 'Medium', 'High']
)

risk_results = X_test.copy()

risk_results['Return_Probability'] = return_probability
risk_results['Risk_Score'] = risk_score
risk_results['Risk_Level'] = risk_level

print(risk_results['Risk_Level'].value_counts())

Risk_Level
Medium    1899
Low        101
High         0
Name: count, dtype: int64

In [87]:
pd.Series(risk_score).describe()

count    2000.000000
mean       50.486735
std         5.935600
min        31.910000
25%        46.655000
50%        50.565000
75%        54.340000
max        66.070000
dtype: float64

In [88]:
data['Order_Month'] = data['Order_Date'].dt.to_period('M').astype(str)

In [92]:
data.head()

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Product_Price,Order_Quantity,User_Age,User_Gender,User_Location,Payment_Method,Shipping_Method,Discount_Applied,Return_Date,Return_Status,Discount_band,Order_Month,Age_Group
0,ORD00000000,PROD00000000,USER00000000,2023-08-05,Clothing,411.59,3,58,Male,City54,Debit Card,Next-Day,45.27,2024-08-26,1,41-50%,2023-08,56-65
1,ORD00000001,PROD00000001,USER00000001,2023-10-09,Books,288.88,3,68,Female,City85,Credit Card,Express,47.79,2023-11-09,1,41-50%,2023-10,66-70
2,ORD00000002,PROD00000002,USER00000002,2023-05-06,Toys,390.03,5,22,Female,City30,Debit Card,Next-Day,26.64,NaT,0,21-30%,2023-05,18-25
3,ORD00000003,PROD00000003,USER00000003,2024-08-29,Toys,401.09,3,40,Male,City95,PayPal,Next-Day,15.37,NaT,0,11-20%,2024-08,36-45
4,ORD00000004,PROD00000004,USER00000004,2023-01-16,Books,110.09,4,34,Female,City80,Gift Card,Standard,16.37,NaT,0,11-20%,2023-01,26-35

In [93]:
data.to_csv('ecommerce_returns_cleaned.csv', index=False)

In [94]:
high_risk = data.loc[X_test.index, [
    'Product_ID',
    'Product_Category',
    'Product_Price',
    'Discount_Applied',
    'Return_Status'
]].copy()

In [95]:
high_risk['Return_Probability'] = return_probability

In [96]:
high_risk['Risk_Score'] = risk_score

In [97]:
high_risk = high_risk.sort_values(
    'Risk_Score',
    ascending=False
)

In [98]:
high_risk.head(20)

,Product_ID,Product_Category,Product_Price,Discount_Applied,Return_Status,Return_Probability,Risk_Score
6759,PROD00006759,Clothing,375.60,40.31,1,0.660667,66.07
3023,PROD00003023,Home,225.51,45.56,1,0.650361,65.04
9038,PROD00009038,Clothing,110.14,27.50,1,0.649413,64.94
740,PROD00000740,Clothing,403.35,48.18,1,0.648607,64.86
4546,PROD00004546,Clothing,59.10,49.35,1,0.648364,64.84
3143,PROD00003143,Electronics,106.75,22.74,1,0.648201,64.82
6586,PROD00006586,Books,28.55,39.82,1,0.648109,64.81
4281,PROD00004281,Clothing,136.40,48.28,0,0.645886,64.59
4478,PROD00004478,Electronics,342.96,39.84,0,0.645845,64.58
9900,PROD00009900,Clothing,109.93,48.38,1,0.645001,64.50
8724,PROD00008724,Clothing,456.95,10.65,0,0.640784,64.08
9665,PROD00009665,Clothing,203.59,29.43,0,0.640289,64.03
3229,PROD00003229,Electronics,390.62,39.91,0,0.639333,63.93
8250,PROD00008250,Home,115.56,35.68,0,0.639167,63.92
1909,PROD00001909,Clothing,157.29,37.58,1,0.637922,63.79
8987,PROD00008987,Toys,176.22,44.84,0,0.637838,63.78
9513,PROD00009513,Clothing,285.58,33.96,0,0.637779,63.78
7187,PROD00007187,Books,36.05,2.21,0,0.637761,63.78
7827,PROD00007827,Toys,74.11,41.75,1,0.637350,63.74
9345,PROD00009345,Clothing,487.57,29.86,0,0.636971,63.70

In [99]:
high_risk.to_csv(
    'high_risk_products.csv',
    index=False
)

In [100]:
print(data.shape)

(10000, 18)

In [101]:
data.head()

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Product_Price,Order_Quantity,User_Age,User_Gender,User_Location,Payment_Method,Shipping_Method,Discount_Applied,Return_Date,Return_Status,Discount_band,Order_Month,Age_Group
0,ORD00000000,PROD00000000,USER00000000,2023-08-05,Clothing,411.59,3,58,Male,City54,Debit Card,Next-Day,45.27,2024-08-26,1,41-50%,2023-08,56-65
1,ORD00000001,PROD00000001,USER00000001,2023-10-09,Books,288.88,3,68,Female,City85,Credit Card,Express,47.79,2023-11-09,1,41-50%,2023-10,66-70
2,ORD00000002,PROD00000002,USER00000002,2023-05-06,Toys,390.03,5,22,Female,City30,Debit Card,Next-Day,26.64,NaT,0,21-30%,2023-05,18-25
3,ORD00000003,PROD00000003,USER00000003,2024-08-29,Toys,401.09,3,40,Male,City95,PayPal,Next-Day,15.37,NaT,0,11-20%,2024-08,36-45
4,ORD00000004,PROD00000004,USER00000004,2023-01-16,Books,110.09,4,34,Female,City80,Gift Card,Standard,16.37,NaT,0,11-20%,2023-01,26-35